<?php

namespace Database\Seeders;

use App\Models\Reference;
use Illuminate\Database\Seeder;

class ReferenceSeeder extends Seeder
{
    public function run(): void
    {
        $references = [
            // Informatique (catégorie 1)
            [
                'title' => 'Introduction à l\'algorithmique',
                'subtitle' => 'Cours et exercices corrigés',
                'abstract' => 'Un ouvrage complet sur les algorithmes fondamentaux avec de nombreux exercices pratiques.',
                'isbn' => '978-2-7462-1234-5',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 450,
                'category_id' => 1,
                'publisher_id' => 2,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
            [
                'title' => 'Programmation Python pour les débutants',
                'subtitle' => 'Apprendre Python pas à pas',
                'abstract' => 'Guide d\'initiation au langage Python avec des exemples concrets.',
                'isbn' => '978-2-7462-1235-2',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 320,
                'category_id' => 1,
                'publisher_id' => 2,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
            [
                'title' => 'Bases de données relationnelles',
                'subtitle' => 'Conception et optimisation',
                'abstract' => 'Approfondissement sur la modélisation et l\'optimisation des bases de données SQL.',
                'isbn' => '978-2-7462-1236-9',
                'publication_year' => 2019,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 380,
                'category_id' => 1,
                'publisher_id' => 3,
                'uploaded_by' => 1,
                'status' => 'published',
            ],

            // Sciences Juridiques (catégorie 2)
            [
                'title' => 'Droit constitutionnel africain',
                'subtitle' => 'Études comparées',
                'abstract' => 'Analyse comparative des constitutions des pays africains francophones.',
                'isbn' => '978-2-7462-2234-5',
                'publication_year' => 2018,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 520,
                'category_id' => 2,
                'publisher_id' => 1,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
            [
                'title' => 'Code civil commenté',
                'subtitle' => 'Obligations et contrats',
                'abstract' => 'Commentaire détaillé du code civil avec jurisprudence récente.',
                'isbn' => '978-2-7462-2235-2',
                'publication_year' => 2022,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 680,
                'category_id' => 2,
                'publisher_id' => 3,
                'uploaded_by' => 1,
                'status' => 'published',
            ],

            // Médecine (catégorie 3)
            [
                'title' => 'Anatomie clinique',
                'subtitle' => 'Atlas et guide pratique',
                'abstract' => 'Atlas d\'anatomie avec applications cliniques pour les étudiants en médecine.',
                'isbn' => '978-2-7462-3234-5',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 750,
                'category_id' => 3,
                'publisher_id' => 3,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
            [
                'title' => 'Pharmacologie fondamentale',
                'subtitle' => 'Mécanismes d\'action des médicaments',
                'abstract' => 'Traité de pharmacologie avec focus sur les mécanismes moléculaires.',
                'isbn' => '978-2-7462-3235-2',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 580,
                'category_id' => 3,
                'publisher_id' => 2,
                'uploaded_by' => 1,
                'status' => 'published',
            ],

            // Sciences Humaines (catégorie 4)
            [
                'title' => 'Sociologie de l\'Afrique contemporaine',
                'subtitle' => 'Dynamiques sociales et culturelles',
                'abstract' => 'Analyse sociologique des transformations des sociétés africaines modernes.',
                'isbn' => '978-2-7462-4234-5',
                'publication_year' => 2019,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 420,
                'category_id' => 4,
                'publisher_id' => 1,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
            [
                'title' => 'Introduction à la psychologie cognitive',
                'subtitle' => 'Processus mentaux et apprentissage',
                'abstract' => 'Fondements de la psychologie cognitive avec applications pédagogiques.',
                'isbn' => '978-2-7462-4235-2',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 360,
                'category_id' => 4,
                'publisher_id' => 2,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
            [
                'title' => 'Philosophie africaine',
                'subtitle' => 'Textes et perspectives',
                'abstract' => 'Anthologie de textes philosophiques africains avec analyses critiques.',
                'isbn' => '978-2-7462-4236-9',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 480,
                'category_id' => 4,
                'publisher_id' => 4,
                'uploaded_by' => 1,
                'status' => 'published',
            ],

            // Sciences Exactes (catégorie 5)
            [
                'title' => 'Mathématiques pour l\'ingénieur',
                'subtitle' => 'Analyse et algèbre',
                'abstract' => 'Cours complet de mathématiques appliquées à l\'ingénierie.',
                'isbn' => '978-2-7462-5234-5',
                'publication_year' => 2022,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 620,
                'category_id' => 5,
                'publisher_id' => 3,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
            [
                'title' => 'Physique quantique',
                'subtitle' => 'Fondements et applications',
                'abstract' => 'Introduction à la mécanique quantique avec exemples d\'applications modernes.',
                'isbn' => '978-2-7462-5235-2',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 540,
                'category_id' => 5,
                'publisher_id' => 2,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
            [
                'title' => 'Chimie organique avancée',
                'subtitle' => 'Synthèse et mécanismes',
                'abstract' => 'Traité de chimie organique avec focus sur les mécanismes réactionnels.',
                'isbn' => '978-2-7462-5236-9',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 720,
                'category_id' => 5,
                'publisher_id' => 3,
                'uploaded_by' => 1,
                'status' => 'published',
            ],

            // Littérature (catégorie 6)
            [
                'title' => 'Contes et légendes d\'Afrique de l\'Ouest',
                'subtitle' => 'Anthologie',
                'abstract' => 'Recueil de contes traditionnels du Mali, du Sénégal et du Burkina Faso.',
                'isbn' => '978-2-7462-6234-5',
                'publication_year' => 2018,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 380,
                'category_id' => 6,
                'publisher_id' => 1,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
            [
                'title' => 'Poésie de la négritude',
                'subtitle' => 'Textes choisis',
                'abstract' => 'Anthologie de poèmes représentatifs du mouvement de la négritude.',
                'isbn' => '978-2-7462-6235-2',
                'publication_year' => 2019,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 280,
                'category_id' => 6,
                'publisher_id' => 4,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
            [
                'title' => 'Théâtre africain contemporain',
                'subtitle' => 'Pièces et analyses',
                'abstract' => 'Recueil de pièces de théâtre africaines avec analyses dramaturgiques.',
                'isbn' => '978-2-7462-6236-9',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'pages' => 450,
                'category_id' => 6,
                'publisher_id' => 2,
                'uploaded_by' => 1,
                'status' => 'published',
            ],
        ];

        foreach ($references as $reference) {
            Reference::create($reference);
        }
    }
}
